### ISSUE TITLE
Inconsistent table name

### ISSUE THREAD

**Issue by Dipta-IIC-EU** [Actyx/Academy-Data#3]
Module's checkpoint: [ax101/sht/vd/eed/end](https://academy.actyx.com/courses/course-v1:Actyx+AX101+2/courseware/5342640fd9d54220b276b68a7df77876/2adc112f42f040928561fb73e4afa248/2)

**Steps to reproduce:**
1. Finish and run module SHT/VD/EED 
2. make sure the first row of the `offset_map` table is filled (e.g. use pgAdmin to check)
3. Stop the DB exporter,  and run it again

**Expected output:**
Because the `offset_map` is no longer empty, db-exporter should NOT show `Could not read OffsetMap from database. That is ok, if the application has not yet pushed events to the DB.`

**Actual output:**
`db-exporter` shows `Could not read OffsetMap from database. That is ok, if the application has not yet pushed events to the DB.`

**Cause:**
https://github.com/Actyx/Academy-Data/blob/ax101/sht/vd/eed/end/ax101/code/course-project/src/db-exporter/db.ts 
Line 80 `if (res.rowCount > 0 && res.rows[0].offsetMap) ` the condition `es.rows[0].offsetMap` will never be `true` (the value will always be `undefined`) because the table name in the db is `offset_map` not `offsetMap`

**Comment by Bato** [comment]
I can reproduce this. 
To solve the problem,  change offestMap with offset_map  in lines 77 , 80 and 81

**Comment by wwerner** [comment]
Thanks for reporting this!
Will fix it tomorrow and let you know once it is live.

**Comment by wwerner** [comment]
Hey @Dipta-IIC-EU, @Bato,

the issue is fixed in `ax101/sht/vd/eed/end` and subsequent branches. This is reflected in the course snippets automatically.

Thanks again for reporting (and also suggesting a fix). Let us know if you stumble upon something again.
