### ISSUE TITLE
The user-facing app machine-terminal crashes while starting

### ISSUE THREAD

**Issue by Bato** [Actyx/Academy-Data#7]
The user-facing app machine-terminal crashes while starting. Error message is: Error: Could not locate the bindings file.

> Module's checkpoint: ax101/tm/ua/pos/end
> Tracking Materials [TM]	User Facing Apps [UA]	Production Order System [POS]

## Steps to reproduce

Run module TM/UA/EED

```sh
cd ~/Academy-Data
git checkout ax101/tm/ua/pos/end
cd ~/Academy-Data/ax101/code/course-project
npm install
# start actyx
/opt/apps/ActyxOS/bin/actyxos-linux

# Start Scanner Simulator
npx @actyx-contrib/actyx-tutorial-simulator ax101-3-scanner --port 1885

#  Start Machine Simulator
npx @actyx-contrib/actyx-tutorial-simulator ax101-3-machine --port 1884

# Start the scanner connector
npm run node:input-material-scanner-connector:start

# Start new machine connector v2
npm run node:machine-connector-v2:start

```

Now start Machine Terminal
```sh
npm run ui:machine-terminal:start
```

## Expected output:

Application Machine Terminal  started successfully

## Actual output:

Error message

``` 
> course-project@1.0.0 ui:machine-terminal:start
> parcel src/machine-terminal/index.html --out-dir build/machine-terminal/debug --port 1235

/opt/src/Actyx/actyx-academy/Academy-Data/ax101/code/course-project/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /opt/src/Actyx/actyx-academy/Academy-Data/ax101/code/course-project/node_modules/deasync/build/deasync.node
 → /opt/src/Actyx/actyx-academy/Academy-Data/ax101/code/course-project/node_modules/deasync/build/Debug/deasync.node
 → /opt/src/Actyx/actyx-academy/Academy-Data/ax101/code/course-project/node_modules/deasync/build/Release/deasync.node
``` 

## Environment:

``` 
node v16.10.0
npm --version 7.24.1
Actyx 2.8.1-5ac08c40ada3b996ea76463462a83f9b35f89993-linux-x86_64-release
Ubuntu 20.04.3 LTS
```

**Comment by wwerner** [comment]
Hi @Bato,

unfortunately, I couldn't reproduce the issue using the same versions you did, but on macOS. For me, it works nicely.
Have you tried removing `node-modules` and running `npm install` again?

Is there anything else that could be different in our environments? I currently don't have an idea what's causing this, let's try to narrow it down.

**Comment by Bato** [comment]
In my environment:
```
node v16.10.0
npm  7.24.1
Actyx 2.8.1-5ac08c40ada3b996ea76463462a83f9b35f89993-linux-x86_64-release
Ubuntu 20.04.3 LTS
```

it is easy to reproduce:
Using 
```sh
    nvm use v13.12.0 
    # Now using node v13.12.0 (npm v6.14.4)
```
everything works fine, and with
```sh
    nvm install 16.10.0
   # Now using node v16.10.0 (npm v7.24.0)
```
starting both UI apps:

  - npm run ui:machine-terminal:start
  - npm run ui:production-order-system:start

throws the same error: Error: Could not locate the bindings file. Tried: ...

> Deleting node-modules and running npm install didn't help unfortunately.

**Comment by wwerner** [comment]
It works for me both using node v13.12.0 and v16.10.0.

However, I can reproduce the behavior if I run `npm install` on v13 and _then_ switch to v16 and run `npm run ui:...:start`.
Removing `node-modules` and (`.cache` to be on the safe side) and reinstalling dependencies then fixes it. 
Installing dependencies using an older node version and then running with a newer one is not expected to work.

To make this more explicit, I added an `.nvmrc` to all checkpoints.

Pulling the latest changes and running 👇  will spin up a working machine terminal.
```
nvm use \
  && rm -rf node_modules/ .cache/ \
  && npm i \
  && npm run ui:machine-terminal:start
```

**Comment by Bato** [comment]
now it also works for me. Thanks for the support!
